name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Install dependencies
    - name: Install Dependencies
      run: npm install

    # Run Cypress tests
    - name: Run Cypress Tests
      run: npm test

    # Save Cypress Videos and Screenshots (optional)
    - name: Upload Artifacts
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-results
        path: |
          cypress/videos
          cypress/screenshots
