name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run ESLint
      - name: Lint JavaScript files
        run: npm run lint

      # Run Cypress tests
      - name: Run Cypress Tests
        run: npm run triggerAllTests-autoTestStore

      # Save Cypress Videos and Screenshots (optional)
      - name: Upload Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots

env:
  BASE_URL: ${{ secrets.BASE_URL }}
